// Barème officiel des points APEXER
export const POINTS = {
  PROFILE_CREATED: 50,
  PLAN_ACTIVATED: 75,
  DAILY_TASK: 10,
  STREAK_7: 25,
  STREAK_21: 50,
  STREAK_66: 150,
  WEEKLY_REVIEW: 20,
  PRINCIPLE_MASTERED: 30,
  BADGE_UNLOCKED: 15,
  COMMUNITY_CHALLENGE: 40,
  REFERRAL: 100,
  // — Étapes de programme (Mont Blanc / Le Lien) —
  STAGE_DIAGNOSTIC_ENTRY: 50,
  STAGE_MISSION_VALIDATED: 20,
  STAGE_OBSERVATION_DONE: 10,
  STAGE_STREAK_3: 30,
  STAGE_STREAK_7: 100,
  STAGE_STREAK_14: 200,
  STAGE_STREAK_21: 500,
  STAGE_WITNESS_COMPLETED: 100,
  STAGE_DIAGNOSTIC_EXIT: 100,
  STAGE_PROGRESSION_15: 150,
} as const

export type PointsReason = keyof typeof POINTS
